spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zadatakmandidb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: debug